name: CI
on:
  pull_request:
  push:
  schedule:
  # 2am EST every Saturday
  - cron: '0 7 * * 6'
jobs:
  build:
    strategy:
      matrix:
        include:
          - java: 8
            distribution: temurin
            sbt: 1
          - java: 8
            distribution: temurin
            sbt: 2
    runs-on: ubuntu-latest
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Scala
      uses: actions/setup-java@v4
      with:
        distribution: "${{ matrix.distribution }}"
        java-version: "${{ matrix.java }}"
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: Build and test (sbt 1.x)
      if: ${{ matrix.sbt == 1 }}
      shell: bash
      run: |
        gpg --import test-key.gpg
        sbt -v ++2.12.x clean scalafmtSbtCheck scalafmtCheckAll test scripted
    - name: Build and test (sbt 2.x)
      if: ${{ matrix.sbt == 2 }}
      shell: bash
      run: |
        gpg --import test-key.gpg
        sbt -v ++3.x clean scalafmtCheckAll test scripted
